server:
  port: 9005
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backend?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 2
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 18000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 5
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池名字
      pool-name: MyHikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: select 1

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml